### ISSUE TITLE
file upload

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-server#173]
#24 The file upload was worked on earlier, but havent fully been tested to work with the client.

**Comment by Joebbrien** [comment]
Did you try testing with Postman file upload?

**Comment by OlivierJM** [comment]
No, I didn't

Actually I should try that, and @Joebbrien if you don't mind you can test it for me, I haven't tried file uploads in Apollo GraphQL, I set up mutations and necessary resolvers.

**Comment by Joebbrien** [comment]
I may need a jump start on GraphQL and Apollo I have not yet read up on that, am sure it cannot be that complex

**Comment by OlivierJM** [comment]
Yep it definitely won't be that complex, 

best thing to do, fork this and clone it then run it, you just need to have mongodb installed and running 
Then go to this url http://localhost:3000/graphiql
you should be able to see the playground, try different things and read the code, you will easily get whats going on.
![Screenshot 2019-10-06 at 3 55 53 PM](https://user-images.githubusercontent.com/11255454/66270287-e1cfd580-e851-11e9-9c27-b8bce7f90558.png)

**Comment by Joebbrien** [comment]
I have cloned the repo, am getting a mongdb network error, on connecting to server

**Comment by Joebbrien** [comment]
Am up and running

**Comment by OlivierJM** [comment]
This is now working with support for multiple file uploads, and filesystem file deletion, just need more optimization, tested from the front-end as well.
