### ISSUE TITLE
getting a mongdb network error, on connecting to server

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-server#175]
I have cloned the repo, am getting a mongdb network error, on connecting to server

_Originally posted by @Joebbrien in https://github.com/SparkEdUAB/sparked-server/issues/173#issuecomment-538753701_

**Comment by OlivierJM** [comment]
@joebbrien this is probably a problem with mongodb not properly connecting
check an env file.
You need an .env file with these contents

```
TOKEN="fortestingifSwiaWF0IjoxNTU5MjAxODk0LCJleHAiOjE1OTA3NTk0OTR9.ZU2zM8kqJAix6m9O52oFLe_bTJTPA8qFewBi9PTbyPA"
GRAPHQL_PORT_DEV = 3000
GRAPHQL_PORT_STAGING = 8080
GRAPHQL_PORT_PROD = 80
MONGO_PORT = 27017
MONGO_URL = "localhost"
dbName = "sparked"
SECRET = "sudfnsjdfnkdsfu48243092incweuchwsomeKeyH3re"
TEST_DB="sparked-test"

```

**Comment by OlivierJM** [comment]
These are the importants envs being used, that should be able to connect you to mongodb, you will need to restart the server.

**Comment by Joebbrien** [comment]
So I noticed, got it fixed with the .env file
